---
title: "Mikropml_practice_chemdataonly"
author: "Nic Chance"
date: "2026-09-08"
output: html_document
---

# Library
```{r}
library(mikropml) #machine learning pipeline to be used to build predictor model
library(readxl) #used to pull in tables/data from excel
```

# Pull in table form excel
```{r}
Data<- read_excel("C:/Users/njchance/OneDrive/Anitamox_influent_data_working.xlsx", sheet=9)
Data.df<- as.data.frame(Data) #make into data frame for mikropml
```

## preprocessing usingl mikropml
```{r}
Data.p<-mikropml::preprocess_data(Data.df, outcome_colname="AmmoniaEFF")
```

## Linear regression
```{r}
results_glmnet<-run_ml(Data.p$dat_transformed, method="glmnet", outcome_colname="AmmoniaEFF", find_feature_importance=TRUE, seed=9826)
```

## Random forest
```{r}
results_rf<-run_ml(Data.p$dat_transformed, method="rf", outcome_colname="AmmoniaEFF", find_feature_importance=TRUE, seed=9826)
results_rf$feature_importance
results_rf$performance
```

## Decision Tree
```{r}
results_dt<-run_ml(Data.p$dat_transformed, method="rpart2", outcome_colname="AmmoniaEFF", find_feature_importance=TRUE, seed=9826)
results_dt$feature_importance
```

## XG Boost
```{r}
results_xg<-run_ml(Data.p$dat_transformed, method="xgbTree", outcome_colname="AmmoniaEFF", find_feature_importance=TRUE, seed=9926)
#this takes very long-run did not complte- will likely be better to just stick to glmnet, dt, and rf like in savannas paper. 
```


# Reduced feature model- chem data only
```{r}
Datar<- read_excel("C:/Users/njchance/OneDrive/Anitamox_influent_data_working.xlsx", sheet=10)
Datar.df<- as.data.frame(Datar) #make into data frame for mikropml
```

## preprocessing usingl mikropml
```{r}
Datar.p<-mikropml::preprocess_data(Datar.df, outcome_colname="AmmoniaEFF")
```

## Linear regression
```{r}
results_glmnet_r<-run_ml(Datar.p$dat_transformed, method="glmnet", outcome_colname="AmmoniaEFF", find_feature_importance=TRUE, kfold=3, seed=9926) #using kfold=3 because it has to be between 1 and number of features
results_glmnet_r$feature_importance
results_glmnet_r$performance # did not do a particular good job
```

## Random forest
```{r}
results_rf_r<-run_ml(Datar.p$dat_transformed, method="rf", outcome_colname="AmmoniaEFF", find_feature_importance=TRUE, kfold=3, seed=9826)
results_rf_r$feature_importance
results_rf_r$performance
```
# ddpcr data- hzsb only
```{r}
Data_pcr<- read_excel("C:/Users/njchance/OneDrive/Anitamox_influent_data_working.xlsx", sheet=11)
Data_pcr.df<- as.data.frame(Data_pcr) #make into data frame for mikropml
```

## Preprocessing
```{r}
Data_pcr.p<-mikropml::preprocess_data(Data_pcr.df, outcome_colname="Ammonia")
```

## Linear regression
```{r}
results_glmnet_pcr<-run_ml(Data_pcr.p$dat_transformed, method="glmnet", outcome_colname="Ammonia", find_feature_importance=TRUE, kfold=3, seed=9926) #using kfold=3 because it has to be between 1 and number of features
results_glmnet_pcr$feature_importance
results_glmnet_pcr$performance
```

## Random forest
```{r}
results_rf_pcr<-run_ml(Data_pcr.p$dat_transformed, method="rf", outcome_colname="Ammonia", find_feature_importance=TRUE, kfold=3, seed=9926) #using kfold=3 because it has to be between 1 and number of features
results_rf_pcr$feature_importance
results_rf_pcr$performance
```

